name: Lactobacillus_delbrueckii

pep_version: 2.1.0

description: "Lactobacillus delbrueckii 27 01 2023"

sample_table: samples.csv

#### RULE CONFIGURATION ####
# rules: set value to TRUE if you want to run the analysis or FALSE if you don't
rules:
  seqfu: TRUE
  mash: TRUE
  fastani: TRUE
  checkm: TRUE
  gtdbtk: FALSE
  prokka-gbk: TRUE
  antismash: TRUE
  query-bigslice: FALSE
  bigscape: TRUE
  bigslice: TRUE
  automlst-wrapper: TRUE
  arts: TRUE
  roary: FALSE
  eggnog: FALSE
  eggnog-roary: FALSE
  deeptfactor: TRUE
  deeptfactor-roary: FALSE
  cblaster-genome: TRUE
  cblaster-bgc: FALSE
  gecco: TRUE
  amrfinderplus: TRUE
