__version__ = "v0.1"

include: "rules/common.smk"

##### Target rules #####

rule all:
    input:
        expand("data/interim/prokka/{strains}/{strains}.gff", strains = STRAINS),
        expand("data/interim/antismash/{strains}/{strains}.gbk", strains = STRAINS),
        "data/interim/roary/",
        "data/interim/bigscape/index.html"

##### Modules #####
include: "rules/ncbi-download.smk"
include: "rules/prokka.smk"
include: "rules/antismash.smk"
include: "rules/roary.smk"
include: "rules/bigscape.smk"