#### RULE CONFIGURATION ####
# rules: set value to TRUE if you want to run the analysis or TRUE if you don't
rules:
  seqfu: TRUE
  mlst: TRUE
  refseq-masher: TRUE
  mash: TRUE
  fastani: TRUE
  checkm: TRUE
  gtdbtk: TRUE
  prokka-gbk: TRUE
  antismash: TRUE
  query-bigslice: TRUE
  bigscape: TRUE
  bigslice: TRUE
  automlst-wrapper: FALSE
  arts: TRUE
  roary: FALSE
  eggnog: TRUE
  eggnog-roary: FALSE
  diamond: TRUE
  diamond-roary: FALSE
  deeptfactor: TRUE
  deeptfactor-roary: FALSE
  cblaster-genome: TRUE
  cblaster-bgc: TRUE