import os, sys
import pandas as pd

def extract_ncbi_information(assembly_report_path, outfile):
    """
    Extract NCBI assembly json reports generated by get_assembly_information.py in a given directory into a csv file 

    Parameters
    ---------- 
    1. assembly_report_path : str / path
        Location of the assembly information json file generated by get_assembly_information.py
    2. outfile : str / path
        Location of the output csv file

    Returns
    -------
    1. outfile : .csv file
        A comma separated table summarizing the NCBI assembly reports metadata
    '''
    """
    ncbi_json_files = [os.path.join(assembly_report_path, f) for f in os.listdir(assembly_report_path) if f.endswith(".json")]

    dfs = [] # an empty list to store the data frames
    for file in ncbi_json_files:
        data = pd.read_json(file).T # read data frame from json file
        dfs.append(data) # append the data frame to the list

    df_ncbi = pd.concat(dfs) # concatenate all the data frames in the list.
    df_ncbi.reset_index(inplace=True)
    df_ncbi  = df_ncbi.rename(columns = {'index':'genome_id'})
    
    df_ncbi.to_csv(outfile, index=False)
    return None

if __name__ == "__main__":
    extract_ncbi_information(sys.argv[1], sys.argv[2])