name: lanthipeptide_lactobacillus
pep_version: 2.1.0
description: 'A selection of lanthipeptides from Lactobacillus delbrueckii'
sample_table: df_antismash_6.1.1_bgc.csv

rules:
  bigslice: TRUE
  bigscape: TRUE
  query-bigslice: TRUE
  clinker: TRUE
  interproscan: TRUE
