suppressPackageStartupMessages({
  library("argparser")
  library("tidyverse")
  library("treeio")
  library("ggtree")
  library("ggtreeExtra")
})

p <- arg_parser(hide.opts = TRUE, 
                paste0("Generates figure 2"))
p <- add_argument(p, "--gtdbtk_tree",
                  short = "-g",
                  help = "Tree file generated by GTDB-tk classify")
p <- add_argument(p, "--bgcs_table",
                  short = "-b",
                  help = "Table with bgcs produced by bgcs_table.R ")
p <- add_argument(p, "--mags_table",
                  short = "-m",
                  help = "Table with mags produced by mags_table.R")
p <- add_argument(p, "--output", 
                  short = "-o", 
                  help = "Filepath for output png figure")

argv <- parse_args(p)


bigscape_classes <- c("Terpene",
                      "RiPPs", 
                      "NRPS",
                      "PKS-NRP_Hybrids",
                      "PKSI",
                      "PKSother", 
                      "Saccharides",
                      "Others")                             

my_classes <- c("Terpene", 
                "RiPP", 
                "NRPS", 
                "NRPS-PKS", 
                "PKS", 
                "PKS", 
                "Other", 
                "Other")


my_colors <- c("#ff8800",
               "#20c200",
               "#ff0000",
               "#dd00ff",
               "#0d00ff",
               "#757575")

levels <- c("domain", 
            "phylum", 
            "class",
            "order", 
            "family",
            "genus", 
            "species")

gtdbtax <- read_csv(argv$mags_table,
                    col_select = c("MAG", "GTDB_tax"), 
                    col_types = "cc")

# Change semicolons in tip names to underscores, 
# since they are incompatible with newick format

tree_text <- gsub(';', '_', readLines(argv$gtdbtk_tree))
tree_text <- gsub('$', ';', tree_text)
tree <- read.newick(text = tree_text)

#Replace NA branch lengths with 0

tree$edge.length <- replace_na(tree$edge.length, 0)

#Subset to our MAGs

reference_tips <- tree$tip.label[str_detect(tree$tip.label, '18-Q3') == FALSE]
mgp1000_tree <- drop.tip(tree, reference_tips)


BGCs_table <- read_csv(argv$bgcs_table, 
                       col_select = c("MAG", "class"), 
                       col_types = "cc")  %>%
  mutate(class = factor(class, levels = bigscape_classes), 
         class = my_classes[as.numeric(class)], 
         class = factor(class, levels = unique(my_classes))) %>%
  group_by(MAG, class) %>%
  tally()

gtdbtax <- read_csv(argv$mags_table, 
         col_select = c("MAG", "GTDB_tax"), 
         col_types = "cc")

find_node_from_taxon <- function(taxon) {
  mags_in_taxon <- gtdbtax$MAG[str_detect(gtdbtax$GTDB_tax, taxon)]
  MRCA(mgp1000_tree, mags_in_taxon)
}


collapse_df <- read_csv(argv$mags_table, 
                  col_select = c("MAG", "GTDB_tax"), 
                  col_types = "cc") %>%
  separate(GTDB_tax, into = levels, sep = ';') %>%
  group_by(phylum) %>%
  mutate(n = n(), 
         label = if_else(n < 60, phylum, class)) %>%
  filter(nchar(label) > 3) %>%
  group_by(label) %>%
  mutate(n = n(), 
         label = if_else(n < 60, label, order)) %>%
  filter(nchar(label) > 3) %>%
  #group_by(label) %>%
  #mutate(n = n(), 
  #       label = if_else(n < 60, label, family)) %>%
  #filter(nchar(label) > 3) %>%
  filter(n > 7) %>%
  group_by(label) %>%
  summarise(node = find_node_from_taxon(label), 
            n = n())



labels_df <- filter(collapse_df, startsWith(label, 'p__') | n > 20)

big_phyla_df <- mutate(gtdbtax, 
                    phylum = str_extract(GTDB_tax, 'p__.*?;'), 
                    phylum = str_sub(phylum, end = -2)) %>%
  group_by(phylum) %>%
  filter(n() > 60) %>%
  group_by(phylum) %>%
  summarize(node = find_node_from_taxon(phylum))

tree1 <- ggtree(mgp1000_tree, aes(color = isTip)) +
  scale_color_manual(values = c("black", "lightgrey"))

add_facet <- function(the_class){
  geom_fruit(data = BGCs_table[BGCs_table$class == the_class,], 
             geom = "geom_bar", 
             mapping = aes(y = MAG, 
                           x = n, 
                           group = label), 
             stat = "identity", 
             orientation = "y",
             fill = my_colors[names(my_colors) == the_class]) 
}

relative_widths <- BGCs_table %>% 
  group_by(class) %>% 
  summarise(n = max(n)) %>% 
  pull(n)

tree2 <- tree1

for (i in 1:length(my_classes)){
  
  nbreaks <- relative_widths[i]/2
  title  <- my_classes[i]
  
  tree2 <- tree2 +
    geom_fruit(data = BGCs_table[BGCs_table$class == my_classes[i],], 
               geom = "geom_bar", 
               mapping = aes(y = MAG, 
                             x = n, 
                             group = label), 
               pwidth = 0.015 * relative_widths[i],
               stat = "identity", 
               orientation = "y",
               fill = my_colors[i], 
               axis.params = list(axis = "x",
                                  text.size = 3,
                                  vjust = 1,
                               #  nbreak = nbreaks,
                                  line.size = NA),
               grid.params = list(vline = FALSE)) 
}



annotated_tree <- tree2  +
  geom_highlight(data = labels_df,
                 mapping = aes(node = node), 
                 fill = NA,
                 color = "lightgray",
                 extend = 10)+
geom_cladelab(data = big_phyla_df, 
               mapping = aes(node = node, label = phylum), 
               geom = "text",
               offset = -2,
              align = TRUE, 
               offset.text = -0.1,
               hjust = 0.5,
               angle = 90) +
  theme(legend.position = "none", 
        strip.background = element_rect(color = "gray95"), 
        strip.text = element_text(size = 10)) 

collapsed_tree <- annotated_tree 

for (row in 1:nrow(collapse_df)) {
  collapsed_tree <- collapse(
    collapsed_tree, 
    clade_name = collapse_df$taxon[row],
    node = collapse_df$node[row], 
    mode = 'mixed',
    color = 'black',
    fill = 'gray95')
  
}

rectangular_tree <- collapsed_tree +  
  geom_cladelab(data = labels_df ,
                mapping = aes(node = node, label = label),
                barsize = NA, 
                geom = 'shadowtext', 
                colour = 'grey',
                bg.colour = 'white', 
                align = TRUE,
                offset = 0.3,
                hjust = 1,
                bg.r = 0.1,
                size =1.5) +
  scale_y_continuous(expand = c(0.02, 1))


ggsave(argv$output, 
       rectangular_tree, 
       device = "png",
       height = 6.9,
       width = 9, 
       units = "in")

