# This file should contain everything to configure the workflow on a global scale.

#### PROJECT INFORMATION ####
# This section control your project configuration. Each project are separated by "-".
# A project must contain the variable "name" and "samples".
# Ideally, a project is a set of genomes of certain clade (pangenome) and can be annotated using a set of well-known reference genomes.
# - name : name of your project
# - samples : a csv file containing a list of genome ids for analysis with multiple sources mentioned. Genome ids must be unique.
# - prokka-db : list of the custom accessions to use as prokka reference database
projects:
  - name: test1
    samples: config/test1/samples.csv
    rules: config/test1/project_config.yaml
    prokka-db: config/test1/prokka-db.csv
    gtdb-tax: config/test1/gtdbtk.bac120.summary.tsv

  - name: test2
    samples: config/test2/samples.csv
    rules: config/test2/project_config.yaml

  - name: test3
    samples: config/test3/samples.csv
    rules: config/test3/project_config.yaml
    prokka-db: config/test3/prokka-db.csv
    gtdb-tax: config/test3/gtdbtk.bac120.summary.tsv

  - name: config/test_pep/project_config.yaml

bgc_projects:
  - pep: config/lanthipeptide_lactobacillus/project_config.yaml


#### GLOBAL RULE CONFIGURATION ####
# This section configures the rules to run globally.
# Use project specific rule configurations if you want to run different rules for each projects.
# rules: set value to TRUE if you want to run the analysis or FALSE if you don't
rules:
  seqfu: FALSE
  mash: FALSE
  fastani: FALSE
  checkm: FALSE
  gtdbtk: FALSE
  prokka-gbk: FALSE
  antismash: TRUE
  query-bigslice: FALSE
  bigscape: FALSE
  bigslice: FALSE
  automlst-wrapper: FALSE
  arts: FALSE
  roary: FALSE
  eggnog: FALSE
  deeptfactor: FALSE
  deeptfactor-roary: FALSE
  cblaster-genome: FALSE
  cblaster-bgc: FALSE

#### RESOURCES CONFIGURATION ####
# resources : the location of the resources to run the rule.
# The default location is at "resources/{resource_name}".
resources_path:
  antismash_db: resources/antismash_db
  eggnog_db: resources/eggnog_db
  BiG-SCAPE: resources/BiG-SCAPE
  bigslice: resources/bigslice
  checkm: resources/checkm
  gtdbtk: resources/gtdbtk
  #RNAmmer: resources/RNAmmer # If specified, will override Barnapp in Prokka

# Check for valid release versions from https://data.gtdb.ecogenomic.org/releases/
# Examples:
# - release 214.1, release_version r214 --> https://data.gtdb.ecogenomic.org/releases/release214/214.1/auxillary_files/gtdbtk_r214_data.tar.gz
# - release 207, release_version r207_v2 --> https://data.gtdb.ecogenomic.org/releases/release207/207.0/auxillary_files/gtdbtk_r207_v2_data.tar.gz

rule_parameters:
  install_gtdbtk:
    release: "214.1"
    release_version: "r214"
  gtdbtk:
    ani_screen: FALSE
  antismash:
    version: "7" # valid versions: 6, 7
  use_gtdb_api: TRUE # Set to false to enable offline mode for taxonomic assignment, see https://github.com/NBChub/bgcflow/wiki/07-Advanced-Configurations#using-gtdb_api-offline-mode

utility_parameters:
  METABASE_MIN_MEMORY: "2g"
  METABASE_MAX_MEMORY: "8g"
  METABASE_VERSION: "v0.47.0"
  METABASE_DUCKDB_PLUGIN_VERSION: "0.2.2"
