# This file should contain everything to configure the workflow on a global scale.

#### PROJECT INFORMATION ####
# This section control your project configuration. Each project are separated by "-".
# A project must contain the variable "name" and "samples".
# Ideally, a project is a set of genomes of certain clade (pangenome) and can be annotated using a set of well-known reference genomes.
# - name : name of your project
# - samples : a csv file containing a list of genome ids for analysis with multiple sources mentioned. Genome ids must be unique.
# - prokka-db : list of the custom accessions to use as prokka reference database
projects:
  - name: test1
    samples: config/test1/samples.csv
    rules: config/test1/project_config.yaml
    prokka-db: config/test1/prokka-db.csv
    gtdb-tax: config/test1/gtdbtk.bac120.summary.tsv

  - name: test2
    samples: config/test2/samples.csv
    rules: config/test2/project_config.yaml

  - name: test3
    samples: config/test3/samples.csv
    rules: config/test3/project_config.yaml
    prokka-db: config/test3/prokka-db.csv
    gtdb-tax: config/test3/gtdbtk.bac120.summary.tsv

  - name: config/test_pep/project_config.yaml

#### GLOBAL RULE CONFIGURATION ####
# This section configures the rules to run globally.
# Use project specific rule configurations if you want to run different rules for each projects.
# rules: set value to TRUE if you want to run the analysis or FALSE if you don't
rules:
  seqfu: FALSE
  mash: FALSE
  fastani: FALSE
  checkm: FALSE
  gtdbtk: FALSE
  prokka-gbk: FALSE
  antismash: TRUE
  query-bigslice: FALSE
  bigscape: FALSE
  bigslice: FALSE
  automlst-wrapper: FALSE
  arts: FALSE
  roary: FALSE
  eggnog: FALSE
  deeptfactor: FALSE
  deeptfactor-roary: FALSE
  cblaster-genome: FALSE
  cblaster-bgc: FALSE

#### RESOURCES CONFIGURATION ####
# resources : the location of the resources to run the rule.
# The default location is at "resources/{resource_name}".
resources_path:
  antismash_db: resources/antismash_db
  eggnog_db: resources/eggnog_db
  BiG-SCAPE: resources/BiG-SCAPE
  bigslice: resources/bigslice
  checkm: resources/checkm
  gtdbtk: resources/gtdbtk
  #RNAmmer: resources/RNAmmer # If specified, will override Barnapp in Prokka
