# This file should contain everything to configure the workflow on a global scale.

#### PROJECT INFORMATION ####
# This section control your project configuration. Each project are separated by "-". 
# A project must contain the variable "name" and "samples".
# Ideally, a project is a set of genomes of certain clade (pangenome) and can be annotated using a set of well-known reference genomes.
# - name : name of your project
# - samples : a csv file containing a list of genome ids for analysis with multiple sources mentioned. Genome ids must be unique.
# - prokka-db : list of the custom accessions to use as prokka reference database
projects:
  - name: dummy_test
    samples: config/samples_test.csv
    prokka-db: config/prokka-db.csv

#### RULE CONFIGURATION ####
# rules: set value to TRUE if you want to run the analysis or FALSE if you don't
rules:
  bigscape: TRUE
  mlst: TRUE
  refseq_masher: TRUE
  seqfu: TRUE
  eggnog: TRUE
  #automlst_wrapper: FALSE # unstable

#### RESOURCES CONFIGURATION ####
# resources : the location of the resources to run the rule. The default location is at "resources/{resource_name}".
resources_path: 
  antismash_db: resources/antismash_db
  eggnog_db: resources/eggnog_db
  BiG-SCAPE: resources/BiG-SCAPE