$schema: "http://json-schema.org/draft-07/schema#"

description: snakemake configuration file

type: object

# possible entries of the config file and which type they should be
properties:
  projects:
    type: array
    items:
      type: object
      properties:
        name:
          type: string
        rules:
          type: string
        samples:
          type: string
        prokka-db:
          type: [string, None]
    uniqueItems: true
    required:
      - name
      - samples
      - rules

  rules:
    type: object
    properties:
      seqfu:
        type: boolean
      mlst:
        type: boolean
      refseq-masher:
        type: boolean
      checkm:
        type: boolean
      prokka-gbk:
        type: boolean
      antismash-summary:
        type: boolean
      antismash-zip:
        type: boolean
      query-bigslice:
        type: boolean
      bigslice:
        type: boolean
      automlst-wrapper:
        type: boolean
      arts:
        type: boolean
      roary:
        type: boolean
      eggnog:
        type: boolean
      eggnog-roary:
        type: boolean

  resources_path:
    type: object
    properties:
      antismash_db:
        type: string
      eggnog_db:
        type: string
      BiG-SCAPE:
        type: string
      RNAmmer:
        type: string


# entries that have to be in the config file for successful validation
required:
  - projects
  - resources_path
