name: test_pep

pep_version: 2.1.0

description: "An example of PEP formatted project"

sample_table: samples.csv
input_folder: "."

prokka-db: prokka-db.csv
#gtdb-tax: gtdbtk.bac120.summary.tsv

#### RULE CONFIGURATION ####
# rules: set value to TRUE if you want to run the analysis or FALSE if you don't
rules:
  seqfu: TRUE
  mash: TRUE
  fastani: TRUE
  checkm: TRUE
  gtdbtk: TRUE
  prokka-gbk: TRUE
  antismash: TRUE
  query-bigslice: TRUE
  bigscape: TRUE
  bigslice: TRUE
  automlst-wrapper: TRUE
  arts: TRUE
  roary: TRUE
  eggnog: TRUE
  eggnog-roary: TRUE
  deeptfactor: TRUE
  deeptfactor-roary: TRUE
  cblaster-genome: TRUE
  cblaster-bgc: TRUE
  gecco: TRUE
