name: lanthipeptide_lactobacillus
pep_version: 2.1.0
description: 'A selection of lanthipeptides from Lactobacillus delbrueckii'
sample_table: df_regions_antismash_7.0.0.csv

rules:
  bigslice: TRUE
  bigscape: TRUE
  query-bigslice: TRUE
  clinker: TRUE
  interproscan: TRUE
  mmseqs2: TRUE
