name: snakemake-actions

on: [push]
jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Formatting
      uses: github/super-linter@v4
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_SNAKEMAKE_SNAKEFMT: true
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Linting
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: .test
        snakefile: workflow/Snakefile
        stagein: "conda config --set channel_priority strict"
        args: "--lint"

  dry-run:
    runs-on: ubuntu-latest
    needs:
      - linting
      - formatting
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Dry-run workflow
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: .test
        snakefile: workflow/Snakefile
        stagein: "conda config --set channel_priority strict"
        args: "--use-conda --show-failed-logs --cores 2 --conda-cleanup-pkgs cache -n"