name: snakemake-actions

on: [push]
jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Formatting
      uses: github/super-linter@v4
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_SNAKEMAKE_SNAKEFMT: true
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Linting
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: .tests
        snakefile: workflow/Snakefile
        stagein: "conda config --set channel_priority strict"
        args: "--lint"

  dry-run:
    runs-on: ubuntu-latest
    needs:
      - linting
      - formatting
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Dry-run workflow
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: .tests
        snakefile: workflow/Snakefile
        stagein: "conda config --set channel_priority strict"
        args: "--use-conda --show-failed-logs --cores 2 --conda-cleanup-pkgs cache -n"

  unit-test:
    runs-on: ubuntu-latest
    needs:
      - dry-run
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install git+https://github.com/NBChub/bgcflow_wrapper.git
      - run: pip install pytest-cov
      - name: Test coverage
        run: pytest --cov=.tests/unit .tests/unit/
      - name: Build coverage file
        run: pytest --cov=.tests/unit .tests/unit/ > pytest-coverage.txt
      - name: Comment coverage
        uses: coroo/pytest-coverage-commentator@v1.0.2
        with:
          pytest-coverage: pytest-coverage.txt
